---
  - name: downloading tomcat
    get_url: 
        url: "{{tomcat_url}}"
        dest: "{{tomcat_dest}}"


  - name: extracting the downloaded tomcat
    unarchive: 
        src: "{{tomcat_dest}}/apache-tomcat-{{tomcat_version}}.tar.gz"
        dest: "{{tomcat_dest}}"
        remote_src: yes


  - name: replacing the server port
    template: 
        src: server.xml.j2
        dest: /opt/apache-tomcat-9.0.36/conf/server.xml


  - name: replacing the tomcat users
    template: 
        src: tomcat-users.xml.j2
        dest: /opt/apache-tomcat-9.0.36/conf/tomcat-users.xm

  - name: replacing the context file
    template: 
        src: context.xml.j2
        dest: /opt/apache-tomcat-9.0.36/webapps/manager/META-INF/context.xml

  - name: starting tomcat
    shell: nohup sh startup.sh &
    args: 
      chdir: "{{tomcat_dest}}/apache-tomcat-{{tomcat_version}}/bin/"
    become: yes
    register: status
    tags: 
    - Running

  - debug: var=status.stdout
    tags: 
    - Running


